name: GitHub Traffic Report

on:
  schedule:
    - cron: "0 8 * * *" # täglich um 08:00 UTC
  workflow_dispatch:

jobs:
  traffic_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests matplotlib

      - name: Run traffic tracking script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          TOKEN_PERSONAL: ${{ secrets.TOKEN_PERSONAL }}
        run: python .github/scripts/internal.py
